ERROR - 2024-10-26 16:20:28 --> Error connecting to the database: mysqli_sql_exception: Host 'localhost' is not allowed to connect to this MariaDB server in C:\xampp\htdocs\PPI\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\PPI\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'zero', 3306, '', 0)
#1 C:\xampp\htdocs\PPI\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\PPI\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\PPI\system\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\PPI\system\Validation\StrictRules\Rules.php(228): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\PPI\system\Validation\Validation.php(336): CodeIgniter\Validation\StrictRules\Rules->is_unique('pedro938493@g2m...', 'email', Array, NULL, 'email')
#6 C:\xampp\htdocs\PPI\system\Validation\Validation.php(201): CodeIgniter\Validation\Validation->processRules('email', 'email', 'pedro938493@g2m...', Array, Array, 'email')
#7 C:\xampp\htdocs\PPI\system\Controller.php(137): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\PPI\app\Controllers\AuthController.php(50): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\PPI\system\CodeIgniter.php(933): App\Controllers\AuthController->realizarCadastro()
#10 C:\xampp\htdocs\PPI\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#11 C:\xampp\htdocs\PPI\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\PPI\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\PPI\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\PPI\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Host 'localhost' is not allowed to connect to this MariaDB server in C:\xampp\htdocs\PPI\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\PPI\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\PPI\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\PPI\system\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#3 C:\xampp\htdocs\PPI\system\Validation\StrictRules\Rules.php(228): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\PPI\system\Validation\Validation.php(336): CodeIgniter\Validation\StrictRules\Rules->is_unique('pedro938493@g2m...', 'email', Array, NULL, 'email')
#5 C:\xampp\htdocs\PPI\system\Validation\Validation.php(201): CodeIgniter\Validation\Validation->processRules('email', 'email', 'pedro938493@g2m...', Array, Array, 'email')
#6 C:\xampp\htdocs\PPI\system\Controller.php(137): CodeIgniter\Validation\Validation->run()
#7 C:\xampp\htdocs\PPI\app\Controllers\AuthController.php(50): CodeIgniter\Controller->validate(Array)
#8 C:\xampp\htdocs\PPI\system\CodeIgniter.php(933): App\Controllers\AuthController->realizarCadastro()
#9 C:\xampp\htdocs\PPI\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#10 C:\xampp\htdocs\PPI\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\PPI\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\PPI\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\PPI\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2024-10-26 16:20:28 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Host 'localhost' is not allowed to connect to this MariaDB server
[Method: POST, Route: cadastro]
in SYSTEMPATH\Database\BaseConnection.php on line 457.
 1 SYSTEMPATH\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `usuarios`
WHERE `email` = :email:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Validation\StrictRules\Rules.php(228): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\Validation\Validation.php(336): CodeIgniter\Validation\StrictRules\Rules->is_unique('pedro938493@g2maill.com2', 'email', [...], null, 'email')
 5 SYSTEMPATH\Validation\Validation.php(201): CodeIgniter\Validation\Validation->processRules('email', 'email', 'pedro938493@g2maill.com2', [...], [...], 'email')
 6 SYSTEMPATH\Controller.php(137): CodeIgniter\Validation\Validation->run()
 7 APPPATH\Controllers\AuthController.php(50): CodeIgniter\Controller->validate([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->realizarCadastro()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
